spring.application.name=sehetak_bethakaa
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/sehetak_db
spring.datasource.username=mohamedsamir
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver


## Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= mohamedkhalilalmasri@gmail.com
spring.mail.password=blpk bzoj iepg decw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

## JWT Configuration
application.security.jwt.secret-key = 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration = 60000
application.security.jwt.refresh-token.expiration = 180000


com.sehetak_bethakaa.appPassword= 5f2D9aG7kL1qV8pW3sZ0xB4mC6tY9hJ2rU7eP1vN8wF3bX6zL0qR5yS4dT7kH2a

#Swagger ui
springdoc.swagger-ui.path=/swagger-ui.html
